create table public.articles (
  id bigint generated by default as identity not null,
  title text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint articles_pkey primary key (id)
);

create index articles_updated_at_idx
  on public.articles (updated_at);

alter table public.articles enable row level security;

revoke all on table public.articles from public, anon, authenticated;
grant select, insert, update, delete on table public.articles to service_role;

create or replace function public.set_articles_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_articles_updated_at()
  from public, anon, authenticated;
grant execute on function public.set_articles_updated_at()
  to service_role;

create trigger articles_set_updated_at
before update on public.articles
for each row
execute function public.set_articles_updated_at();
