SET local check_function_bodies = off;

CREATE TABLE "public"."clients" (
  "id"               bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"       timestamp with time zone    NOT NULL DEFAULT now(),
  "user_telegram_id" character varying,
  "first_name"       character varying,
  "last_name"        character varying,
  "last_message_at"  timestamp without time zone NOT NULL,
  CONSTRAINT "clients_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."clients"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."messages" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "author"             character varying,
  "body"               text,
  "messenger_user_id"  character varying,
  "messenger_type"     character varying,
  "client_id"          bigint                   NOT NULL,
  "telegram_update_id" bigint,
  CONSTRAINT "messages_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."messages"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.save_telegram_message (
  p_update_id  bigint,
  p_user_id    text,
  p_first_name text,
  p_last_name  text,
  p_author     text,
  p_body       text,
  p_sent_at    timestamp with time zone
)
  RETURNS void
  LANGUAGE plpgsql
  SET search_path TO ''
  AS $function$
declare
  saved_client_id bigint;
begin
  insert into public.clients (user_telegram_id, first_name, last_name, last_message_at)
  values (p_user_id, p_first_name, p_last_name, p_sent_at at time zone 'UTC')
  on conflict (user_telegram_id) do update set
    first_name = case when excluded.last_message_at >= clients.last_message_at
      then excluded.first_name else clients.first_name end,
    last_name = case when excluded.last_message_at >= clients.last_message_at
      then excluded.last_name else clients.last_name end,
    last_message_at = greatest(clients.last_message_at, excluded.last_message_at)
  returning id into saved_client_id;

  insert into public.messages (
    telegram_update_id, created_at, author, body,
    messenger_user_id, messenger_type, client_id
  ) values (
    p_update_id, p_sent_at, p_author, p_body,
    p_user_id, 'telegram', saved_client_id
  )
  on conflict (telegram_update_id) do nothing;
end;
$function$;

ALTER TABLE "public"."messages"
  ADD CONSTRAINT "messages_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id);

CREATE UNIQUE INDEX clients_user_telegram_id_key ON public.clients USING btree (user_telegram_id);

CREATE INDEX messages_client_created_id_idx ON public.messages USING btree (client_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX messages_telegram_update_id_key ON public.messages USING btree (telegram_update_id);

REVOKE ALL ON FUNCTION "public"."save_telegram_message"(bigint, text, text, text, text, text, timestamp WITH time zone) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."save_telegram_message"(bigint, text, text, text, text, text, timestamp WITH time zone) TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."clients" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."messages" TO "anon", "authenticated", "postgres", "service_role";

