create table public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_telegram_id character varying null,
  first_name character varying null,
  last_name character varying null,
  last_message_at timestamp without time zone not null,
  constraint clients_pkey primary key (id),
  constraint clients_user_telegram_id_key unique (user_telegram_id)
) TABLESPACE pg_default;

create table public.messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  author character varying null,
  body text null,
  messenger_user_id character varying null,
  messenger_type character varying null,
  client_id bigint not null,
  telegram_update_id bigint null,
  constraint messages_pkey primary key (id),
  constraint messages_client_id_fkey foreign key (client_id) references public.clients (id),
  constraint messages_telegram_update_id_key unique (telegram_update_id)
) TABLESPACE pg_default;
